### ISSUE TITLE
Not syncing with Notion

### ISSUE THREAD

**Issue by Adi1505-macintosh** [yannick-cw/notionfy#11]
I did everything as mentioned above. It evens shows me the following on terminal:

Welcome
Done syncing new highlights to Notion
Shutting down

But my notion page is still empty.

**Comment by sgomezp** [comment]
Hi! I'm having the same problem.
Thanks :-)

**Comment by yannick-cw** [comment]
Thanks for letting me know, might be that there was an api change, I’ll investigate

**Comment by yannick-cw** [comment]
Okay I just tried, it still works for me, can you run it with the `--verbose` flag and report the output?

**Comment by sgomezp** [comment]
Hi @yannick-cw,
[output.txt](https://github.com/yannick-cw/notionfy/files/5125497/output.txt)

I attach a file with the last part of my output
The output is so long that the command window doesn't let me browse up
Btw, I'm using windows 10
Thank you so much

**Comment by Adi1505-macintosh** [comment]
@yannick-cw 
This is the output I got after adding --verbose:

_Welcome
Reading highlights from Kindle at /Volumes/Kindle....
Done readingkindhle highlights
Parsed kindle highlights to internal format
Fetching highlights from Notion...
Fetched current highlghts from Notion

Found Highlights:



Syncing new highlights:

....

Done syncing new highlights to Notion
Shutting down_

**Comment by yannick-cw** [comment]
@Adi1505-mac this looks like there actually are no highlights 
Can you verify that your `kindlePath / "documents" / "My Clippings.txt"` is filled with some highlights?
@sgomezp I'll have a look on the weekend, thanks, looks like some network issues, or possible too many highlights?
Maybe you could check how many lines your `kindlePath \ "documents" \ "My Clippings.txt"` has.

**Comment by sgomezp** [comment]
Hi @yannick-cw 
Please, take your time, no problem.
You are right,  `"My Clipping.txt"` file has too many highlights. It has 5443 lines! 😮
Do I have to delete some highlights in order for the program to works?
Thank you so much and have a nice weekend!

**Comment by yannick-cw** [comment]
@sgomezp wow not bad! Active reader I guess :) No please do not delete any, this should work no problem.

**Comment by Adi1505-macintosh** [comment]
@yannick-cw 
The 'MyCliipings.txt' file is not empty but I still get no highlights on Notion. That's weird.

**Comment by yannick-cw** [comment]
@Adi1505-mac can you post me an excerpt of your clippings file? Maybe it has to do with language or another formatting.

**Comment by yannick-cw** [comment]
@sgomezp I moved your problem to https://github.com/yannick-cw/notionfy/issues/13 as they seem not related

**Comment by yannick-cw** [comment]
@Adi1505-mac it would be great if you could run it again with the `0.2.4` version. I improved the logging and we should see more of whats going on. Same for @sgomezp, but please report in #13

**Comment by Adi1505-macintosh** [comment]
@yannick-cw 
The new 0.2.4 version gives me the following error:

```
Exception in thread "main" com.oracle.svm.core.jdk.UnsupportedFeatureError: Invoke with MethodHandle argument could not be reduced to at most a single call or single field access. The method handle must be a compile time constant, e.g., be loaded from a `static final` field. Method that contains the method handle invocation: java.lang.invoke.LambdaForm$MH/1966367130.invoke_MT(Object, Object)
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:86)
	at scala.runtime.Statics.releaseFence(Statics.java:148)
	at scala.collection.immutable.$colon$colon.<init>(List.scala:586)
	at scala.collection.mutable.ListBuffer.addAll(ListBuffer.scala:120)
	at scala.collection.mutable.ListBuffer$.from(ListBuffer.scala:38)
	at scala.collection.immutable.List$.from(List.scala:617)
	at scala.collection.IterableOnceOps.toList(IterableOnce.scala:1234)
	at scala.collection.IterableOnceOps.toList$(IterableOnce.scala:1234)
	at scala.collection.AbstractIterable.toList(Iterable.scala:921)
	at cats.effect.internals.IOAppPlatform$.mainFiber(IOAppPlatform.scala:37)
	at cats.effect.internals.IOAppPlatform$.main(IOAppPlatform.scala:24)
	at cats.effect.IOApp.main(IOApp.scala:67)
	at cats.effect.IOApp.main$(IOApp.scala:66)
	at com.monovore.decline.effect.CommandIOApp.main(CommandIOApp.scala:10)
	at notionfys.Main.main(Main.scala)
```

**Comment by yannick-cw** [comment]
@Adi1505-mac could you 
`brew reinstall yannick-cw/homebrew-tap/notionfy` reinstall and try again?

**Comment by Adi1505-macintosh** [comment]
@yannick-cw 
Upon trying it recently this is what I get:

```
Welcome


Unfortunately syncing failed, you can run with --verbose to see more details about what is going on. Please report the output to https://github.com/yannick-cw/notionfys, so I can fix it. Here is the error:

java.net.MalformedURLException: Accessing an URL protocol that was not enabled. The URL protocol https is supported but not enabled by default. It must be enabled by adding the -H:EnableURLProtocols=https option to the native-image command.
```

**Comment by yannick-cw** [comment]
could you download `0.2.4` again and try again?

**Comment by alook90** [comment]
Hi @yannick-cw,

thank you for your efforts. I really like the project. I am also dealing with the problem @Adi1505-mac already mentioned. 

I reinstalled via brew some minutes ago and the verbose output is as follows:

```
Welcome
Reading highlights from Kindle at /Volumes/Kindle....
Done reading kindle highlights

Found Highlights locally:

[...]

Parsed kindle highlights to internal format
Fetching highlights from Notion...


Unfortunately syncing failed, you can run with --verbose to see more details about what is going on. Please report the output to https://github.com/yannick-cw/notionfys, so I can fix it. Here is the error:

java.net.MalformedURLException: Accessing an URL protocol that was not enabled. The URL protocol https is supported but not enabled by default. It must be enabled by adding the -H:EnableURLProtocols=https option to the native-image command.
sttp.client.SttpClientException$.defaultExceptionToSttpClientException(SttpClientException.scala:32)
sttp.client.HttpURLConnectionBackend.$anonfun$adjustExceptions$1(HttpURLConnectionBackend.scala:287)
sttp.client.SttpClientException$.adjustSynchronousExceptions(SttpClientException.scala:50)
sttp.client.HttpURLConnectionBackend.adjustExceptions(HttpURLConnectionBackend.scala:287)
sttp.client.HttpURLConnectionBackend.send(HttpURLConnectionBackend.scala:28)
sttp.client.HttpURLConnectionBackend.send(HttpURLConnectionBackend.scala:22)
sttp.client.FollowRedirectsBackend.sendWithCounter(FollowRedirectsBackend.scala:29)
sttp.client.FollowRedirectsBackend.send(FollowRedirectsBackend.scala:17)
sttp.client.RequestT.send(RequestT.scala:279)
notionfys.Notion$.$anonfun$reqRes$1(Notion.scala:100)
cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:87)
cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:355)
cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:376)
cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:316)
cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
cats.effect.internals.PoolUtils$$anon$2$$anon$3.run(PoolUtils.scala:51)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)
com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
```

```
>notionfy --version
0.2.4
```

**Comment by yannick-cw** [comment]
Please try with `0.2.5`, I think the issue should be resolved now!

**Comment by Adi1505-macintosh** [comment]
@yannick-cw I still don't see any highlights. I am not sure where I am going wrong. The MyClippings.txt file is not empty and I have got the page id and token_v2 right. Also I did reinstall to get `0.2.5` but it still shows the version as `0.2.4`

```
Welcome
Reading highlights from Kindle at /Volumes/Kindle....
Done reading kindle highlights

Found Highlights locally:


Parsed kindle highlights to internal format
Fetching highlights from Notion...
Fetched current highlights from Notion

Found Highlights in Notion:



Syncing new highlights:

....

Done syncing new highlights to Notion
Shutting down
```

**Comment by yannick-cw** [comment]
@Adi1505-mac okay this looks good at least now. It seems you clippings file format is somehow not parse-able. Could you send me and extract or the full one? You could also email it to me directly.

**Comment by Adi1505-macintosh** [comment]
@yannick-cw Ok, I have mailed my My Clippings.txt file to you.

**Comment by yannick-cw** [comment]
Did you ever do anything by hand to your clippings file? It seems to be there are some malformed things in there (but not breaking).
To get it to work, delete the first line of the file ;), that worked for me locally

**Comment by Adi1505-macintosh** [comment]
@yannick-cw Sorry, I didn't get you there. First line of the txt file? That seems to be the book name. Won't it delete that then?

**Comment by alook90** [comment]
@yannick-cw: works fine. Thank you very much!

**Comment by yannick-cw** [comment]
@Adi1505-mac yes this line `﻿CRACKING THE CODE:` is somehow malformed and does not belong there

**Comment by Adi1505-macintosh** [comment]
@yannick-cw OMG! Thank You, it worked 👍
