### ISSUE TITLE
First time syncing error

### ISSUE THREAD

**Issue by XerxesD** [yannick-cw/notionfy#14]
Hi Yannick, 
Thank you for this, I am trying to run this for the first time but its not working. Here is the error output: 

Http request failed while decoding the response with: Attempt to decode value on failed cursor: DownField(notion_user),DownField(recordMap) and body: {"recordMap":{"block":{"cdc39453-9c96-45dd-aef7-4e48653320da":{"role":"editor","value":{"id":"cdc39453-9c96-45dd-aef7-4e48653320da","version":35,"type":"page","properties":{"title":[["Kindle Highlights"]]},"content":["7ba39254-69bc-40b6-85be-ce4aaa72c769","ffcbcf58-b701-4dd0-867e-f0176451ddb5"],"permissions":[{"role":"editor","type":"user_permission","user_id":"f1384d98-f0a4-4d8f-8254-4764e20de0b6"}],"created_time":1600534260000,"last_edited_time":1600539540000,"parent_id":"29812eab-0ae2-41d6-9d5a-5a0600e1151f","parent_table":"space","alive":true,"created_by_table":"notion_user","created_by_id":"f1384d98-f0a4-4d8f-8254-4764e20de0b6","last_edited_by_table":"notion_user","last_edited_by_id":"f1384d98-f0a4-4d8f-8254-4764e20de0b6","shard_id":70943,"space_id":"29812eab-0ae2-41d6-9d5a-5a0600e1151f"}},"7ba39254-69bc-40b6-85be-ce4aaa72c769":{"role":"editor","value":{"id":"7ba39254-69bc-40b6-85be-ce4aaa72c769","version":21,"type":"text","properties":{"title":[["token_v2\t60e7834a0e0140a9a7bc9b6ad383b1fd6e064f73ace16ccfd4d54a180c379e1af9135f9de0ce50aca234f1ffedcbdb218f345992a399bd0b4156997ceab28ff11280e7e440b9d00b24ee4f38fe95"]]},"created_time":1600534320000,"last_edited_time":1600539540000,"parent_id":"cdc39453-9c96-45dd-aef7-4e48653320da","parent_table":"block","alive":true,"created_by_table":"notion_user","created_by_id":"f1384d98-f0a4-4d8f-8254-4764e20de0b6","last_edited_by_table":"notion_user","last_edited_by_id":"f1384d98-f0a4-4d8f-8254-4764e20de0b6","shard_id":70943,"space_id":"29812eab-0ae2-41d6-9d5a-5a0600e1151f"}},"ffcbcf58-b701-4dd0-867e-f0176451ddb5":{"role":"editor","value":{"id":"ffcbcf58-b701-4dd0-867e-f0176451ddb5","version":8,"type":"text","created_time":1600534800000,"last_edited_time":1600534800000,"parent_id":"cdc39453-9c96-45dd-aef7-4e48653320da","parent_table":"block","alive":true,"created_by_table":"notion_user","created_by_id":"f1384d98-f0a4-4d8f-8254-4764e20de0b6","last_edited_by_table":"notion_user","last_edited_by_id":"f1384d98-f0a4-4d8f-8254-4764e20de0b6","shard_id":70943,"space_id":"29812eab-0ae2-41d6-9d5a-5a0600e1151f"}}},"space":{"29812eab-0ae2-41d6-9d5a-5a0600e1151f":{"role":"editor","value":{"id":"29812eab-0ae2-41d6-9d5a-5a0600e1151f","version":89,"name":"Xerxes","domain":"serdest","permissions":[{"role":"editor","type":"user_permission","user_id":"f1384d98-f0a4-4d8f-8254-4764e20de0b6"}],"beta_enabled":false,"pages":["a31c5bff-d49a-4d90-9588-8b097d52993f","b710ee09-0995-42be-b712-34e2fa1d3a7a","be1e31a2-1549-4c54-9189-58ca668eacce","2f8554cb-778c-40da-949b-2f552d4937fa","dc09e0e9-4e5d-4d75-b18c-0cf46ab903ae","81c6ed06-41a5-43a2-a215-174bc39fb664","4bc34bae-17b5-4618-a11d-14550ab5f0fb","cdc39453-9c96-45dd-aef7-4e48653320da"],"created_by":"f1384d98-f0a4-4d8f-8254-4764e20de0b6","created_time":1568821020000,"last_edited_by":"f1384d98-f0a4-4d8f-8254-4764e20de0b6","last_edited_time":1600534260000,"created_by_table":"notion_user","created_by_id":"f1384d98-f0a4-4d8f-8254-4764e20de0b6","last_edited_by_table":"notion_user","last_edited_by_id":"f1384d98-f0a4-4d8f-8254-4764e20de0b6","shard_id":70943,"plan_type":"personal","invite_link_code":"0e955ccfcd9ef768d45728220d04b9ce313777ae","invite_link_enabled":false}}}},"cursor":{"stack":[]}}

**Comment by yannick-cw** [comment]
Thanks I'll look into that!

**Comment by yannick-cw** [comment]
I am sorry for the delay, I had some vacation and so on..
I released 0.2.6, please see if it helps. Notion had an api change, which made notionfy fail. It should be fine now, otherwise please send me your verbose output here and I'll try.

**Comment by XerxesD** [comment]
Thanks for working on this! 
But there is still an issue: 

Http request failed while decoding the response with: Attempt to decode value on failed cursor: DownField(notion_user),DownField(recordMap) and body: {"recordMap":{"block":{"0fa14832-aeb7-44b6-a578-08d69bf5930e":{"role":"editor","value":{"id":"0fa14832-aeb7-44b6-a578-08d69bf5930e","version":11,"type":"page","content":["91919741-7c52-4ef6-8059-56f599a8d677"],"permissions":[{"role":"editor","type":"user_permission","user_id":"f1384d98-f0a4-4d8f-8254-4764e20de0b6"}],"created_time":1602512340000,"last_edited_time":1602535440000,"parent_id":"29812eab-0ae2-41d6-9d5a-5a0600e1151f","parent_table":"space","alive":true,"created_by_table":"notion_user","created_by_id":"f1384d98-f0a4-4d8f-8254-4764e20de0b6","last_edited_by_table":"notion_user","last_edited_by_id":"f1384d98-f0a4-4d8f-8254-4764e20de0b6","shard_id":70943,"space_id":"29812eab-0ae2-41d6-9d5a-5a0600e1151f"}},"91919741-7c52-4ef6-8059-56f599a8d677":{"role":"editor","value":{"id":"91919741-7c52-4ef6-8059-56f599a8d677","version":8,"type":"text","created_time":1602535440000,"last_edited_time":1602535440000,"parent_id":"0fa14832-aeb7-44b6-a578-08d69bf5930e","parent_table":"block","alive":true,"created_by_table":"notion_user","created_by_id":"f1384d98-f0a4-4d8f-8254-4764e20de0b6","last_edited_by_table":"notion_user","last_edited_by_id":"f1384d98-f0a4-4d8f-8254-4764e20de0b6","shard_id":70943,"space_id":"29812eab-0ae2-41d6-9d5a-5a0600e1151f"}}},"space":{"29812eab-0ae2-41d6-9d5a-5a0600e1151f":{"role":"editor","value":{"id":"29812eab-0ae2-41d6-9d5a-5a0600e1151f","version":124,"name":"Xerxes","domain":"serdest","permissions":[{"role":"editor","type":"user_permission","user_id":"f1384d98-f0a4-4d8f-8254-4764e20de0b6"}],"beta_enabled":false,"pages":["0fa14832-aeb7-44b6-a578-08d69bf5930e","a31c5bff-d49a-4d90-9588-8b097d52993f","b710ee09-0995-42be-b712-34e2fa1d3a7a","be1e31a2-1549-4c54-9189-58ca668eacce","2f8554cb-778c-40da-949b-2f552d4937fa","dc09e0e9-4e5d-4d75-b18c-0cf46ab903ae","81c6ed06-41a5-43a2-a215-174bc39fb664","4bc34bae-17b5-4618-a11d-14550ab5f0fb","f0ba3706-49ca-48b9-a71b-41f01e523280"],"created_by":"f1384d98-f0a4-4d8f-8254-4764e20de0b6","created_time":1568821020000,"last_edited_by":"f1384d98-f0a4-4d8f-8254-4764e20de0b6","last_edited_time":1602512340000,"created_by_table":"notion_user","created_by_id":"f1384d98-f0a4-4d8f-8254-4764e20de0b6","last_edited_by_table":"notion_user","last_edited_by_id":"f1384d98-f0a4-4d8f-8254-4764e20de0b6","shard_id":70943,"plan_type":"personal","invite_link_code":"0e955ccfcd9ef768d45728220d04b9ce313777ae","invite_link_enabled":false}}}},"cursor":{"stack":[]}}

**Comment by yannick-cw** [comment]
@XerxesD are you sure you are on `0.2.6`? On what operating system? `notion_user` is not in part of `0.2.6` any more, so I guess you are on `0.2.5`

**Comment by XerxesD** [comment]
It works now thanks! 
I think the problem was that I installed 0.2.5 using brew but used the zip for 0.2.6.
Now I updated with the upgrade command in the terminal and it worked! 

Thank you so much, this is really great!
